python-setup-steps: &python-setup-steps
  language: python
  install:
    - pip install pipenv
    - pipenv install --dev
    - sudo apt-get install ninja-build

windows-setup-steps: &windows-setup-steps
  os: windows
  language: cpp  #Python is not yet supported on Windows
  install:
    - choco install python2
    - py -m pip install pipenv
    - py -m pipenv install --dev

matrix:
  include:
    - name: "Linux: test with ninja on python 2.7"
      os: linux
      python: '2.7'
      compiler: clang
      <<: *python-setup-steps
      script: pipenv run -v test -f ninja

    - name: "osx: test with ninja on python 2.7"
      os: osx
      osx_image: xcode9.3
      python: '2.7'
      compiler: clang
      <<: *python-setup-steps
      script: pipenv run -v test -f ninja

    - name: "Windows: test with ninja on python 2.7"
      <<: *windows-setup-steps
      script: pipenv run -v test -f ninja

    - name: "Windows: test with make on python 2.7"
      <<: *windows-setup-steps
      script: pipenv run -v test -f make

    - name: "Linux: test with make on python 2.7"
      python: '2.7'
      compiler: clang
      <<: *python-setup-steps
      script: pipenv run -v test -f make

    - name: "lint with python 2.7"
      python: '2.7'
      <<: *python-setup-steps
      script: pipenv run -v lint

    - name: "lint with python 3.7"
      python: '3.7'
      dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
      <<: *python-setup-steps
      script: pipenv run -v lint

    - name: "lint shell scripts"
      language: shell
      install:
        - shellcheck --version  # Travis defaults to v0.4.6
        - wget -qO- "https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz" | tar -xJv
        - shellcheck-stable/shellcheck --version  # Current is v0.6.0
      script: bash -c 'shopt -s globstar ; shellcheck-stable/shellcheck **/*.{sh,ksh,bash}'

  allow_failures:
    - os: windows
    - language: shell
    - os: osx
    - os: windows

notifications:
  slack: node4good:C2EI9vo04FY8Ce5u7kcOLlDw
